name: Build and Push Docker Image Tag 'mcp-ollama'

on:
  push:
    branches: [main]
    paths:
      - 'mcp-ollama/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./mcp-ollama/Dockerfile
          push: true
          tags: stefankuhnakros/windsurf-ollama-integration:mcp-ollama
